name: vue-dev
services:
  backend-dev:
    image: planterson/vue-backend-dev
    container_name: vue-backend-dev
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - ../env/dev.env
    volumes:
      - ../server.js:/backend/server.js:ro
    entrypoint: ["npm", "run", "dev"]
    