services:
  backend:
    image: planterson/vue-node-backend
    container_name: vue-backend
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - 80:80
    volumes:
      - ./server.js:/backend/server.js:ro
    entrypoint: ["npm", "run", "dev"]