name: vue-dev

services:
  mongodb-dev:
    image: "mongo"
    ports:
      - 27017:27017
    volumes:
      - data-dev:/data/db:rw
    container_name: mongodb-dev
    env_file:
      - ../backend/env/.env.mongodb-dev

  backend-dev:
    image: planterson/vue-backend-dev
    container_name: vue-backend-dev
    build:
      context: ../backend/
      target: development
    ports:
      - 5000:5000
    env_file:
      - ../backend/env/.env.dev
    volumes:
      - ../backend/src:/backend/src:ro
      - ../backend/key.pem:/backend/key.pem:ro
      - ../backend/cert.pem:/backend/cert.pem:ro
    depends_on:
      - mongodb-dev
    entrypoint: ["npm", "run", "dev"]

  frontend-dev:
    image: planterson/vue-frontend-dev
    container_name: vue-frontend-dev
    build:
      context: ../frontend/
      target: development
    ports:
      - "5173:5173"
    env_file:
      - ../frontend/env/.env.local
    volumes:
      - ../frontend/src/:/frontend/src/:ro
      - ../frontend/index.html:/frontend/index.html:ro

    stdin_open: true
    tty: true
    entrypoint: ["npm", "run", "dev"]

volumes:
  data-dev: