name: vue-prod

services:
  mongodb-prod:
    image: "mongo"
    volumes:
      - data-prod:/data/db:rw
    container_name: mongodb-prod
    env_file:
      - ../backend/env/.env.mongodb-prod

  backend-prod:
    container_name: backend-prod
    hostname: backend
    image: planterson/vue-backend-prod
    build:
      context: ../backend/
      dockerfile: dockerfiles/Dockerfile.prod
    env_file:
      - ../backend/env/.env.prod
    # ports:
    #   - 80:80
    depends_on:
      - mongodb-prod
    entrypoint: [ "npm", "start" ]

  frontend-prod:
    container_name: frontend-prod
    hostname: frontend
    depends_on:
      - backend-prod
    image: planterson/vue-frontend-prod
    build:
      context: ../frontend/
      dockerfile: dockerfiles/Dockerfile.prod
    ports:
      - 80:80
    stdin_open: true
    tty: true
    entrypoint: [ "nginx", "-g", "daemon off;" ]
