name: vue-prod

services:
  mongodb-prod:
    image: "mongo"
    volumes:
      - data-prod:/data/db:rw
    container_name: mongodb-prod
    env_file:
      - ../backend/env/.env.mongodb-prod

  backend-prod:
    container_name: backend-prod
    hostname: backend
    image: planterson/vue-backend-prod
    build:
      context: ../backend/
      target: production
    env_file:
      - ../backend/env/.env.prod
    depends_on:
      - mongodb-prod
    volumes:
      - ../backend/key.pem:/backend/key.pem:ro
      - ../backend/cert.pem:/backend/cert.pem:ro
    entrypoint: [ "npm", "start" ]

  frontend-prod:
      container_name: frontend-prod
      hostname: frontend
      image: planterson/vue-frontend
      build:
        context: ../frontend
        target: production
      ports:
        - 80:80
        - 443:443
      stdin_open: true
      tty: true
      volumes:
        - ../frontend/dhparam.pem:/etc/nginx/dhparam.pem:ro
        - ../frontend/nginx.crt:/etc/ssl/certs/nginx.crt:ro
        - ../frontend/nginx.key:/etc/ssl/private/nginx.key:ro
      entrypoint: [ "nginx", "-g", "daemon off;" ]

volumes:
  data-prod: