services:
  frontend:
    image: planterson/vue-frontend
    container_name: vue-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    entrypoint: ["npm", "run", "dev"]