name: vue-dev

services:
  mongodb-dev:
    image: "mongo"
    volumes:
      - data-dev:/data/db:rw
    container_name: mongodb-dev
    env_file:
      - ../env/.env.mongodb-dev

  backend-dev:
    image: planterson/vue-backend-dev
    container_name: vue-backend-dev
    build:
      context: ../
      target: development
    ports:
      - 5000:5000
    env_file:
      - ../env/.env.dev
    volumes:
      - ../src/:/backend/src/:ro
    depends_on:
      - mongodb-dev
    entrypoint: ["npm", "run", "dev"]

volumes:
  data-dev:
