name: vue-prod
services:
  mongodb-prod:
    image: "mongo"
    volumes:
      - data-prod:/data/db:rw
    container_name: mongodb-prod
    env_file:
      - ../env/.env.mongodb-prod

  backend-prod:
    image: planterson/vue-backend-prod
    container_name: vue-backend-prod
    hostname: backend
    build:
      context: ../
      target: production
    env_file:
      - ../env/.env.prod
    # ports:
    #   - 80:80
    depends_on:
      - mongodb-prod
    entrypoint: [ "npm", "start" ]

volumes:
  data-prod: