name: vue-dev
services:
  frontend-dev:
    image: planterson/vue-frontend-dev
    container_name: vue-frontend
    build:
      context: ../
      target: development
    ports:
      - "5173:5173"
    env_file:
      - ../env/.env.local
    volumes:
      - ../src/:/frontend/src:ro
    stdin_open: true
    tty: true
    entrypoint: ["npm", "run", "dev"]