name: vue-prod
services:
  frontend-prod:
      container_name: frontend-dev
      hostname: frontend
      image: planterson/vue-frontend-dev
      build:
        context: ../
        target: production
      ports:
        - 80:80
        - 443:443
      stdin_open: true
      tty: true
      volumes:
        - ../dhparam.pem:/etc/nginx/dhparam.pem:ro
        - ../nginx.crt:/etc/ssl/certs/nginx.crt:ro
        - ../nginx.key:/etc/ssl/private/nginx.key:ro
      entrypoint: [ "nginx", "-g", "daemon off;" ]
