name: vue-dev
services:
  frontend-dev:
    image: planterson/vue-frontend
    container_name: vue-frontend
    build:
      context: ../
      dockerfile: dockerfiles/Dockerfile.dev
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    entrypoint: ["npm", "run", "dev"]